[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet publish RaizesStore.Api/RaizesStore.Api.csproj -c Release -o /app/publish --self-contained false"
]

[start]
cmd = "dotnet /app/publish/RaizesStore.Api.dll"
